### ISSUE TITLE
Error processing config

### ISSUE THREAD

**Issue by andyzasl** [kwirk/yidashcam#1]
```
Traceback (most recent call last):
  File "sync.py", line 5, in <module>
    print("Serial number: {}".format(yi.serial_number))
  File "/Users/andy/tmp/yidashcam/yidashcam/__init__.py", line 308, in serial_number
    return self.config[config.Option.serial_number]
  File "/Users/andy/tmp/yidashcam/yidashcam/__init__.py", line 256, in config
    config_et = ET.fromstring(self._send_cmd(Command.config))
  File "/Users/andy/tmp/yidashcam/yidashcam/__init__.py", line 130, in _send_cmd
    res_xml = ET.fromstring(res.text)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 44, column 34
```

**Comment by kwirk** [comment]
Looks like it's not happy with the XML the camera returned. Could you try going to the following link in your web browser and posting what's returned: http://192.168.1.254/?custom=1&cmd=3014

**Comment by kwirk** [comment]
Interestingly line 44 in my XML is the serial number, one of the few string fields in the camera's config; it could be an invalid XML character in the serial number...

**Comment by andyzasl** [comment]
--   Trying 192.168.1.254...
-- Connected to 192.168.1.254 (192.168.1.254) port 80 (#1)
>> GET /?custom=1&cmd=3014 HTTP/1.1
>> Host: 192.168.1.254
>> User-Agent: libcurl/7.50.1 OpenSSL/1.0.1t zlib/1.2.5 nghttp2/1.13.0
>> Accept: */*
>> Connection: Upgrade, HTTP2-Settings
>> Upgrade: h2c
>> HTTP2-Settings: AAMAAABkAAQAAP__
>> 
>> 
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 100
Content-type: text/xml
Connection: close

<?xml version="1.0" encoding="UTF-8" ?>
<Function>
<Cmd>3014</Cmd>
<Status>-256</Status>
</Function>-- Closing connection 1

** Timing Details **
-- 	Name Lookup:	0.00s
-- 	TCP Connect: 	0.13s
-- 	First Byte: 		0.34s
-- 	Total Download: 	1.40s
-- Size: 100 bytes
-- Speed: 71 bytes/sec
-- Using: HTTP/1.1
** RESULT CODE: 200**

**Comment by andyzasl** [comment]
This from phone, sorry

**Comment by andyzasl** [comment]
```--   Trying 192.168.1.254...
-- Connected to 192.168.1.254 (192.168.1.254) port 80 (#1)
>> GET /?custom=1&cmd=3014 HTTP/1.1
>> Host: 192.168.1.254
>> User-Agent: libcurl/7.50.1 OpenSSL/1.0.1t zlib/1.2.5 nghttp2/1.13.0
>> Accept: */*
>> Connection: Upgrade, HTTP2-Settings
>> Upgrade: h2c
>> HTTP2-Settings: AAMAAABkAAQAAP__
>> 
>> 
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 100
Content-type: text/xml
Connection: close

<?xml version="1.0" encoding="UTF-8" ?>
<Function>
<Cmd>3014</Cmd>
<Status>-256</Status>
</Function>-- Closing connection 1

** Timing Details **
-- 	Name Lookup:	0.00s
-- 	TCP Connect: 	0.13s
-- 	First Byte: 		0.34s
-- 	Total Download: 	1.40s
-- Size: 100 bytes
-- Speed: 71 bytes/sec
-- Using: HTTP/1.1
** RESULT CODE: 200**```

**Comment by kwirk** [comment]
Sorry; forgot you need to send connect command first. Could you go to the following links in order:
- http://192.168.1.254/?custom=1&cmd=8001
- http://192.168.1.254/?custom=1&cmd=3014

**Comment by andyzasl** [comment]
```
--   Trying 192.168.1.254...
-- Connected to 192.168.1.254 (192.168.1.254) port 80 (#1)
>> GET /?custom=1&cmd=3014 HTTP/1.1
>> Host: 192.168.1.254
>> User-Agent: libcurl/7.50.1 OpenSSL/1.0.1t zlib/1.2.5 nghttp2/1.13.0
>> Accept: */*
>> Connection: Upgrade, HTTP2-Settings
>> Upgrade: h2c
>> HTTP2-Settings: AAMAAABkAAQAAP__
>> 
>> 
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 100
Content-type: text/xml
Connection: close

<?xml version="1.0" encoding="UTF-8" ?>
<Function>
<Cmd>3014</Cmd>
<Status>-256</Status>
</Function>-- Closing connection 1

** Timing Details **
--  Name Lookup:    0.00s
--  TCP Connect:    0.13s
--  First Byte:         0.34s
--  Total Download:     1.40s
-- Size: 100 bytes
-- Speed: 71 bytes/sec
-- Using: HTTP/1.1
** RESULT CODE: 200**
```

**Comment by andyzasl** [comment]
I'll grab other responses tomorrow :(

**Comment by andyzasl** [comment]
The first one:

```
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 97
Content-type: text/xml
Connection: close

<?xml version="1.0" encoding="UTF-8" ?>
<Function>
<Cmd>8001</Cmd>
<Status>0</Status>
</Function>
```

And the second one:

```
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 100
Content-type: text/xml
Connection: close

<?xml version="1.0" encoding="UTF-8" ?>
<Function>
<Cmd>3014</Cmd>
<Status>-256</Status>
</Function>
```

**Comment by kwirk** [comment]
Looks like the second URL wasn't called soon enough after the first (the `-256` status means not connected); the second URL needs to be followed a within ~10 seconds of the first. Sorry my instructions weren't very clear. The response should be something like:

```
<Function>
<Cmd>1002</Cmd>
<Status>0</Status>
<Cmd>2016</Cmd>
<Status>0</Status>
<Cmd>2002</Cmd>
<Status>0</Status>
<Cmd>2003</Cmd>
<Status>1</Status>
<Cmd>2004</Cmd>
<Status>1</Status>
<Cmd>2005</Cmd>
<Status>6</Status>
<Cmd>2006</Cmd>
<Status>0</Status>
<Cmd>2007</Cmd>
<Status>0</Status>
<Cmd>2008</Cmd>
<Status>1</Status>
<Cmd>2011</Cmd>
<Status>0</Status>
<Cmd>2012</Cmd>
<Status>0</Status>
<Cmd>3007</Cmd>
<Status>0</Status>
<Cmd>3008</Cmd>
<Status>0</Status>
<Cmd>3009</Cmd>
<Status>0</Status>
<Cmd>3012</Cmd>
<Status>V-1.01.005-US</Status>
<Cmd>3032</Cmd>
<Status>0</Status>
<Cmd>3033</Cmd>
<Status>1</Status>
<Cmd>2020</Cmd>
<Status>0</Status>
<Cmd>3041</Cmd>
<Status>1</Status>
<Cmd>3035</Cmd>
<Status>YICARCAM</Status>
<Cmd>3037</Cmd>
<Status>SERIALNUMBER123</Status>
<Cmd>2030</Cmd>
<Status>0</Status>
<Cmd>2031</Cmd>
<Status>0</Status>
<Cmd>2040</Cmd>
<Status>0</Status>
<Cmd>2050</Cmd>
<Status>0</Status>
<Cmd>2051</Cmd>
<Status>1</Status>
</Function>
```

**Comment by andyzasl** [comment]
I done this, the second request reply: 

```
HTTP/1.1 200 OK
Server: hfs/1.00.000
Cache-Control:no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
Content-length: 1020
Content-type: text/xml
Connection: close
```

Looks like there is empty answer :(

**Comment by kwirk** [comment]
That's strange, as the content-length is declared to be 1020 bytes, which is about right for configuration XML output. The original error message made reference to line 44, which means an output must have come back before. Not sure what to suggest...

**Comment by andyzasl** [comment]
Don't know if it related to CN to US reflashing camcoder, with serial change.

**Comment by kwirk** [comment]
Could be. Does the serial number look okay when you go on info section of the actual camera UI?

**Comment by andyzasl** [comment]
Yes

4 окт. 2016 г., 19:36 +0300, Steven Hiscocks notifications@github.com, писал:

**Comment by andyzasl** [comment]
Yes, it's ok

**Comment by kwirk** [comment]
Another thing you could try is connecting to the camera in Python (or _stream_ mode from command line tool), so we know a proper connection has been made, and then in a seperate terminal try the second URL with cURL or use your web browser.
