### ISSUE TITLE
seems to not working

### ISSUE THREAD

**Issue by mccob** [kwirk/yidashcam#4]
Seems to not working anymore (see logs behind).

Firmware version : V-1.03.026-US (last)

```
127.0.0.1 - - [08/May/2017 19:44:20] "GET /favicon.ico/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1547, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\webapp.py", line 85, in error_500_handler
    return render_template("error.html", message=error), 500
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 764, in update_template_context
    context.update(func())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\webapp.py", line 110, in yi_context
    context['serial_number'] = yi.serial_number
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__init__.py", line 307, in serial_number
    return self.config[config.Option.serial_number]
KeyError: <Option.serial_number: 3037>
```

**Comment by kwirk** [comment]
I'm using the same firmware version, and I'm not seeing any issues. Could you try running `python -m yidashcam config` and see if any errors are reported.

**Comment by mccob** [comment]
```
>python -m yidashcam config
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__main__.py", line 86, in <module>
    yi.config.items(), key=lambda x: x[0].name)],
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__init__.py", line 255, in config
    config_et = ET.fromstring(self._send_cmd(Command.config))
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__init__.py", line 131, in _send_cmd
    res_xml = ET.fromstring(res.text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 46, column 32

```

I may have miss something but don't know what.

Thank you

**Comment by mccob** [comment]
May it's because of an issue with S/N of dashcam,  : 
<Status>CA21WSUSCA1610F098C5(¶£ë0</Status>

After stripping incorrect chars, I have that : 
```
>python -m yidashcam config
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__main__.py", line 86, in <module>
    yi.config.items(), key=lambda x: x[0].name)],
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\yidashcam\__init__.py", line 255, in config
    config_et = ET.fromstring(self._send_cmd(Command.config))
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 46, column 32



```

**Comment by mccob** [comment]
Ok it's the same issue.

I have to see why my S/N is malformed.

Solved by stripping incorrect chars : .replace('(¶£ë0','') (lines 131 & 255)

Close the issue

**Comment by kwirk** [comment]
This looks like the same issue seen in #1. Not sure why some cameras have strange characters on the serial number. If it was consistent, I could add your fix, but it may be different cameras will have different junk on the end of the serial number.

May be related: do you have a Chinese camera, which you modified the serial number in order to flash US firmware? (I also did this, but I don't have issues)

**Comment by mccob** [comment]
exact ! Chinese model with modified S/N

I will check the format of S/N

If think the solution is to found how to encode chinese chars to avoid XML errors
