### ISSUE TITLE
Syntax error right away

### ISSUE THREAD

**Issue by GMFalka** [kwirk/yidashcam#6]
Hello!

i have the chinese version and i did not tried modifying anything (no SN hackery)
Installed everything and i get this error:

```
$ python -m yidashcam
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/yidashcam/__init__.py", line 359
    yield from self._send_cmd(Command.file_thumbnail, path, stream=True)
             ^
SyntaxError: invalid syntax
```

**Comment by GMFalka** [comment]
I was using python 2.7... Fixed.
